/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_calculator_free(a: number): void;
export function calculator_new(): number;
export function calculator_add_expense(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): number;
export function calculator_add_ower_to_expense(a: number, b: number, c: number, d: number): number;
export function calculator_print_expenses(a: number, b: number): void;
export function calculator_get_result(a: number, b: number): void;
export function calculator_get_currencies(a: number, b: number): void;
export function calculator_confirm_currency(a: number, b: number, c: number, d: number): void;
export function calculator_update_target_currency(a: number, b: number, c: number): number;
export function calculator_calculate(a: number, b: number): void;
export function greet(): void;
export function __wbgt_should_create_request_0(a: number): void;
export function __wbg_wasmbindgentestcontext_free(a: number): void;
export function wasmbindgentestcontext_new(): number;
export function wasmbindgentestcontext_args(a: number, b: number, c: number): void;
export function wasmbindgentestcontext_run(a: number, b: number, c: number): number;
export function __wbgtest_console_log(a: number): void;
export function __wbgtest_console_debug(a: number): void;
export function __wbgtest_console_info(a: number): void;
export function __wbgtest_console_warn(a: number): void;
export function __wbgtest_console_error(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha7a59fb1f64e9625(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__h218690321d440258(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke3_mut__h2970a19e68ab198a(a: number, b: number, c: number, d: number, e: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h025189b833907f36(a: number, b: number, c: number, d: number): void;
